### ISSUE TITLE
optional resolved fields fails to resolve

### ISSUE THREAD

**Issue by Dambre** [allmonday/pydantic2-resolve#11]
Hey, I am migrating from v1 of this library and found an interesting behavior with resolved fields. Working version:

```
x: Optional[X] = None
def resolve_x(...):
   ...
```
But all of my models were defined using this syntax:
```
x: X | None = None
```
And it throws:
<img width="348" alt="image" src="https://github.com/allmonday/pydantic2-resolve/assets/9976600/b18c858c-77e0-471a-9c6d-eeb70f5a5eb1">

_pydantic2-resolve=2.1.1_

**Comment by allmonday** [comment]
https://github.com/allmonday/pydantic2-resolve/issues/7#issuecomment-2041501779

this is described in this issue.
